name: pln2-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - PyPDF2
      - pinecone
      - langchain-text-splitters
      - sentence-transformers==3.0.1
      - torch==2.2.1
      - transformers==4.39.3
      - numpy<2
      - streamlit
      - groq
      - huggingface_hub==0.19.4
